# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      
  # Enable version updates for rust (example project)
  - package-ecosystem: "cargo"
    directory: "/examples/notifications-demo/"
    schedule:
      interval: "weekly"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for npm (example project)
  - package-ecosystem: "npm"
    directory: "/examples/notifications-demo/"
    schedule:
      interval: "weekly"

  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "weekly"

  # Enable version updates for Gradle (example project)
  - package-ecosystem: "gradle"
    directory: "/examples/notifications-demo/src-tauri/gen/android/"
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
